OwnWork/urls.py
from django.urls import path, re_path, include

from .views import index, article, newest, create

urlpatterns = [
    path('', index, name='home'),
    path('newest/', newest, name='new'),
    path('article-<int:id>/', article, name='article'),
    path('create/', create, name='create'),
]

SABAH/urls.py
from django.urls import path, re_path, include

from .views import controller, article

urlpatterns = [
    path('', controller),
    path('article-<int:id>/', article),
]

Yasper/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('SABAH.urls')),
    path('', include('OwnWork.urls')),
]

OwnWork/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    about = models.TextField()
    profile_image = models.ImageField()

    def __str__(self) -> str:
        return f"{self.name} {self.surname}"

class Article(models.Model):
    title = models.CharField(max_length=256)
    author = models.ForeignKey(Account, on_delete=models.DO_NOTHING)
    content = models.TextField()
    published = models.DateTimeField()

    def __str__(self) -> str:
        return f"{self.title}"

SABAH/models.py
from django.db import models

# Create your models here.

# class Author(models.Model):
#     Name = models.CharField(max_length=32)
#     Surname = models.CharField(max_length=32)

#     class Meta:
#         verbose_name = "Author"
#         verbose_name_plural = "Authors"

# class Article(models.Model):
#     Title = models.CharField(max_length=64)
#     Author = models.ForeignKey(Author, on_delete=models.CASCADE)
#     Tag = models.CharField(max_length=16)
#     Content = models.TextField()
#     Published = models.TimeField()
#     Views = models.IntegerField()

#     class Meta:
#         verbose_name = "Article"
#         verbose_name_plural = "Articles"

class Author(models.Model):
    Name = models.CharField(max_length=32, verbose_name="Имя")
    Surname = models.CharField(max_length=32, verbose_name="Фамилия")

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"
        
    def __str__(self) -> str:
        return f"{self.Name} {self.Surname}"

class Article(models.Model):
    Title = models.CharField(max_length=64, verbose_name="Заголовок")
    Author = models.ForeignKey(Author, verbose_name="Автор", on_delete=models.DO_NOTHING)
    Tag = models.CharField(max_length=16, verbose_name="Метка")
    Content = models.TextField(verbose_name="Содержимое")
    Published = models.DateTimeField(verbose_name="Дата Публикации")
    Views = models.IntegerField(verbose_name="Количество Просмотров", default=0)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
    
    def __str__(self) -> str:
        return f"{self.Title}, опубликованно {self.Published} {self.Views}"

OwnWork/forms.py
from django import forms
from datetime import datetime as dt

from .models import Article, Account

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'author', 'content', 'published']
        widgets = dict(
            content = forms.Textarea(attrs={
                'rows':18,
            }),
            published = forms.DateTimeInput(attrs={
                'type':'datetime-local',
            }),
        )

        def __init__(self, *args, **kwargs) -> None:
            super(ArticleForm, self).__init__(*args, **kwargs)

        

OwnWork/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .models import Article, Account
from .forms import ArticleForm
# Create your views here.
def index(request):
    return render(request, 'index.html', dict(articles=Article.objects.all()[:10]))

def article(request, id):
    return render(request, 'article.html', dict(article=Article.objects.get(id=id)))

def newest(request):
    return render(request, 'index.html', dict(articles=Article.objects.order_by("-published")[:10]))

def create(request):
    if request.method == "GET":
        return render(request, 'form.html', dict(form=ArticleForm(use_required_attribute=False)))
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, use_required_attribute=False)
        if form.is_valid():
            new_article = form.save()
            return redirect('article', id=new_article.id)
        
        err = []
        for field in form.fields.keys():
            if form.has_error(field):
                err.append(field)
                form.fields[field].widget.attrs['class'] = 'error'

        return render(request, 'form.html', dict(form=form, errors=err))
    

SABAH/views.py
from django.shortcuts import render, HttpResponse
from urllib.parse import unquote

from .models import Article, Author
# Create your views here.

def controller(request):
    articles = Article.objects.all()
    d = {}
    for i in articles:
        if i.Tag not in d.keys():
            d[i.Tag] = 1
        else:
            d[i.Tag] += 1

    if request.GET.get("tag", True) == True:
        return main(request)
    return category(request)

def main(request):
    articles = Article.objects.all()
    d = {}
    for i in articles:
        if i.Tag not in d.keys():
            d[i.Tag] = 1
        else:
            d[i.Tag] += 1
    
    return render(request, "index.html", dict(
        tags=list(sorted(d.items(), key=lambda x:x[1], reverse=True)[:3]),
        articles=articles
    ))

def category(request):
    articles = Article.objects.all()
    d = {}
    for i in articles:
        if i.Tag not in d.keys():
            d[i.Tag] = 1
        else:
            d[i.Tag] += 1
    
    return render(request, "index.html", dict(
        tags=list(sorted(d.items(), key=lambda x:x[1], reverse=True)[:3:]),
        articles=Article.objects.filter(Tag=unquote(request.GET.get("tag")))
    ))

def article(request, id):
    articles = Article.objects.all()
    d = {}
    for i in articles:
        if i.Tag not in d.keys():
            d[i.Tag] = 1
        else:
            d[i.Tag] += 1

    article = articles.filter(id=id)[0]
    article.Views += 1
    article.save()

    return render(request, "article.html", dict(
        tags=list(sorted(d.items(), key=lambda x:x[1], reverse=True)[:3]),
        articles=articles.filter(id=id)
    ))

OwnWork/templates/abbr/navbar.html
<nav class="navbar">
    <a href="{% url 'home' %}" class="navbar-brand">
        <span class="brand-1">I</span><span class="brand-2">NEWS</span>
    </a>
    <ul class="menu">
        <li class="menu-item">
            <a href="{% url 'home' %}" class="item {% if request.path == '/' %}active{% endif %}">Main</a>
        </li>
        <li class="menu-item">
            <a href="{% url 'new' %}" class="item {% if request.path == '/newest' or request.path == '/newest/' %}active{% endif %}">Newest</a>
        </li>
        <li class="menu-item">
            <a href="{% url 'create' %}" class="item {% if request.path == '/create' or request.path == '/create/' %}active{% endif %}">Create</a>
        </li>
    </ul>
</nav>

OwnWork/templates/article.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{article.title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
<body>
    
    {% include 'abbr/navbar.html' %}
    <br><br><br><br>
    <article>
        <div class="article-info">
            <a href="#" class="article-author-image">
                <img src="{% static 'assets/' %}{{article.author.profile_image}}" alt="Profile's Image" width="64" height="64">
            </a>
            <div>
                <p>by <a class="article-author" href="writer-{{article.author.id}}">{{article.author.name}} {{article.author.surname}}</a></p>
                <h1>{{article.title}}</h1>
            </div>
        </div>
        <div class="content">
            <div class="context" style="height: fit-content;">
                {% autoescape off %}
                    {{article.content}}
                {% endautoescape %}
            </div>
        </div>
    </article>

</body>
</html>

OwnWork/templates/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        {% for e in errors %}
            label[for=id_{{e}}] {
                color: #d62d2d;
            }
        {% endfor %}
    </style>
</head>
<body>
    
    {% include 'abbr/navbar.html' %}
    <br><br><br>
    <form name="article" action="{% url 'create' %}" method="POST">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        {{form.title}}

        <label for="id_author">Author:</label>
        {{form.author}}

        <label for="id_content">Content:</label>
        {{form.content}}

        <label for="id_published">Published:</label>
        {{form.published}}

        <input type="submit" value="submit">
    </form>
</body>
</html>

OwnWork/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>inews</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
<body>
    
    {% include 'abbr/navbar.html' %}

    <!-- <header>

        {% with ''|center:3 as range %}
        {% for _ in range %}
            <section>
                <img src="{% static 'assets/desert.jpg' %}" alt="Section's Image">
                <div class="section-content">
                    <h1>This is Titile about something large text for wrap or overflow -ing. This is Titile about something large text for wrap or overflow -ing</h1>

                    {% with ''|center:12 as range2 %}
                    <p>{% for __ in range2 %}It's same with the title this link view about something of nothing.{% endfor %}</p>
                    {% endwith %}

                    <a href="#">Read More</a>
                </div>
            </section>
        {% endfor %}
        {% endwith %}

    </header> -->

    <br><br><br><br>
    {% for article in articles %}
        <article>
            <div class="article-info">
                <a href="#" class="article-author-image">
                    <img src="{% static 'assets/' %}{{article.author.profile_image}}" alt="Profile's Image" width="64" height="64">
                </a>
                <div>
                    <p>by <a class="article-author" href="writer-{{article.author.id}}">{{article.author.name}} {{article.author.surname}}</a></p>
                    <h1>{{article.title}}</h1>
                </div>
            </div>
            <div class="content">
                <div class="context">
                    {% autoescape off %}
                        {{article.content}}
                    {% endautoescape %}
                </div>

                <a href="{% url 'article' id=article.id %}">Read More</a>
            </div>
        </article>
    {% endfor %}

</body>
</html>

SABAH/templates/article.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
{% endblock links %}

{% block navigation %}
    {% include 'abbr\nabvar.html' %}
{% endblock navigation %}

{% block content %}
{% if articles|length == 0 %}
    <br><br>
    <h1 style="text-align: center; color: #0F4C75;">:( Статьи не найдены.</h1>
{% else %}
    
    {% for a in articles %}

        <article>
            <br><h2>{{a.Title}}</h2><h4>{{a.Tag}}</h4><hr color="#0F4C75">
            <br><br>
            <p style="-webkit-box-orient: unset;">
                {{a.Content}}
            </p>
            <br>
            <p>Посмотрели: {{a.Views}}</p>
            <p>Опубликовано: {{a.Published}}</p>
            <br>
        </article>
        <br><br>

    {% endfor %}

{% endif %}
{% endblock content %}

SABAH/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    {% block links %}
    
    {% endblock links %}
</head>
<body>
    {% block navigation %}

    {% endblock navigation %}

        
        <div style="width: 70vw; margin: 35px 15vw;">
            <h2 style="text-align: center; color: #3282B8;">Найденные Статьи</h2>
            <hr color="#3282B8">
        </div>

    {% block content %}

    {% endblock content %}

    <br><br>
    <footer>
        <h1>Created By Ibad</h1>
        <h3>NOT STEAL!!!</h3>
    </footer>
</body>
</html>

SABAH/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/article.css' %}">
{% endblock links %}

{% block navigation %}
    {% include 'abbr\nabvar.html' %}
{% endblock navigation %}

{% block content %}
{% if articles|length == 0 %}
    <br><br>
    <h1 style="text-align: center; color: #0F4C75;">:( Статьи не найдены.</h1>
{% else %}
    
    {% for a in articles %}

        <article>
            <br><h2>{{a.Title}}</h2><h4>{{a.Tag}}</h4><hr color="#0F4C75">
            <br><br>
            <p>
                {{a.Content}}
            </p>
            <br>
            <div>
                <p>Посмотрели: {{a.Views}}</p>
                <a href="article-{{a.id}}">Посмотреть</a>
            </div>
            <br>
        </article>
        <br><br>

    {% endfor %}

{% endif %}
{% endblock content %}